spring:
  datasource:
    url: jdbc:mysql://docker:3306/buffer_id?useSSL=false
    hikari:
      auto-commit: true
      jdbc-url: jdbc:mysql://docker:3306/buffer_id?useSSL=false
      username: root
      password: 123456
      minimum-idle: 1
      maximum-pool-size: 100
      idle-timeout: 300000
      max-lifetime: 1200000
  redis:
    host: docker
    password: 123456
    jedis:
      pool:
        max-idle: 100
        max-active: 200
        min-idle: 10
        max-wait: 30000